### ISSUE TITLE
how to make this program work

### ISSUE THREAD

**Issue by stewcop** [AdamRakaska/GNFS#9]
Even running this program with the default settings loaded in i was unable to make this program run properly

**Comment by stewcop** [comment]
here is my output log if that helps

[Output.log.txt](https://github.com/AdamWhiteHat/GNFS/files/4478077/Output.log.txt)

**Comment by AdamWhiteHat** [comment]
Thank you so much for supplying your Output.log.txt, this helped immensely. 

After reviewing the log, I surmise that you were attempting to run the pre-compiled binary file /GNFS/Binaries/Debug/GNFS-Winforms.exe checked into the main branch of this project. 
If that was the case, then the reason the application didn't run was no fault of your own; the files were 1) missing a critical library: Polynomial.dll (I extracted this code and made it a nuget package) and 2) were out of date with the latest code.

I have just updated the files there, plus included the much-needed Polynomial.dll. Please try re-downloading (from https://github.com/AdamWhiteHat/GNFS/tree/master/Binaries/) and replacing the files with the new ones, and let me know if that doesnt fix the problem.

Thank you for bringing this issue to my attention. Feel free to open new tickets for new or separate issues.

Thank you for your interest in my project.
